// This file is generated by pnpm db:generate.
export default {
  journal: {
    version: "7",
    dialect: "sqlite",
    entries: [
      {
        idx: 0,
        version: "6",
        when: 1789728826035,
        tag: "0000_cuddly_shaman",
        breakpoints: true,
      },
    ],
  },
  migrations: {
    m0000:
      "CREATE TABLE `jobs` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`kind` text NOT NULL,\n\t`dueAt` integer NOT NULL,\n\t`payload` text NOT NULL,\n\t`attempt` integer NOT NULL,\n\t`generation` text NOT NULL\n);\n--> statement-breakpoint\nCREATE INDEX `jobs_due` ON `jobs` (`dueAt`,`id`);",
  },
};
